### PR TITLE
Fix require paths

### PR DESCRIPTION
**Pull request by c0m3tx**
Regarding rake issue #179, this should work for everyone.

Requires changing the require line from ```require 'rake/contrib/ftptools'``` to ```require 'rake-contrib/ftptools'``` (for instance)

Updated tests to match the new lib structure.

### CODE REVIEW

**Comment by drbrain** [comment]
From ruby/rake#179 you expect `require 'rake/contrib/ftptools'` to work, but this pull request doesn't allow that to work, you must change your require line.

Changing what you have to require isn't backward-compatible, so the next version must be 2.0.0.

**Comment by c0m3tx** [comment]
@drbrain thanks for the information. I updated the gem version to 2.0.0.

**Comment by drbrain** [comment]
I'm still confused how this fixes the problem from ruby/rake#179.

**Comment by c0m3tx** [comment]
It seems that for some reason requiring rake then rake-contrib (which happens if you require rake-contrib inside a rakefile) with the previous path makes Ruby look in the same folder, and therefore raises an error as the file cannot be found. However, just renaming the folder makes it look again in the gem folder, resolving the issue. 

Don't know if it's an issue which only happens on my side, but I'm open for any information request.

**Comment by drbrain** [comment]
Then it is probably a rubygems bug and not a rake/rake-contrib bug.

**Comment by c0m3tx** [comment]
Are you able to reproduce the issue? If not, please let me know how else I can help.

**Pull request closed without merging**
